version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  test-react:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "react-app/package-lock.json"}}
      # CircleCI seems to start a new terminal when you run each script
      - run: cd react-app && npm ci
      - save_cache:
        # Need to add the path for the package-lock file or the checksum fails!
          key: dependency-cache-{{ checksum "react-app/package-lock.json"}}
          paths:
            - ./node_modules
  build-app:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "react-app/package-lock.json"}}
      - run: cd react-app && npm run build
      # Persisting the build folder
      - persist_to_workspace:
          root: .
          paths:
            - react-app/build
  deploy-to-aws:
    executor:
      name: node/default
    # Access env vars from CircleCI
    steps:
      - attach_workspace:
          at: ./react-app/build
      - run: ls -R
      - aws-cli/setup:
        profile-name: default
      - run:
        name: Upload file to S3
        command: aws s3 sync ./react-app/build/ s3://greenerinteriors --delete

# CI Workflow/ Pipeline
workflows:
  build-deploy:
    jobs:
      - test-react
      - build-app:
          requires:
            - test-react
      - deploy-to-aws:
          requires:
            - build-app
          # Add AWS Context based env vars in
          context: aws-context
