version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  hello:
    executor:
      name: node/default
    steps:
      - echo 'Hello there!'
  checkout:
    executor:
      name: node/default
    steps:
      - checkout
      - run: node --version
      - run: npm --version
workflows:
    checkout:
      jobs:
        - hello
        - checkout